name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-2019
    defaults:
      run:
        working-directory: package/windows

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -f Dockerfile -t fluentd-windows:$(date +%s)
